version: '2'
services:
  keycloak:
    image: "jboss/keycloak"
    ports:
     - "8081:8080"
     - "9991:9990"
    volumes:
     - ./keyCloak_configuration:/var/tmp
     - ./themes/tw-wh:/opt/jboss/keycloak/themes/tw-wh
    environment:
     - KEYCLOAK_USER=admin 
     - KEYCLOAK_PASSWORD=password
    # entrypoint: /opt/jboss/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/var/tmp    
    command:
     - -b 0.0.0.0
     - -Dkeycloak.migration.action=import
     - -Dkeycloak.migration.provider=dir 
     - -Dkeycloak.migration.dir=/var/tmp